#!/bin/bash

echo "=== Install NodeJS ==="
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install nodejs
sudo npm install forever fibers underscore source-map-support semver -g
npm install forever fibers underscore source-map-support semver
sudo mv node_modules /home/arsnova

echo "=== Install and configure MongoDB ==="
sudo apt-get install mongodb
sudo systemctl enable mongodb.service
sudo systemctl start mongodb.service
mongo < mongodb_config.js
sudo systemctl restart mongodb.service
systemctl status mongodb.service

echo "=== Install and configure Nginx ==="
sudo useradd -m meteor
sudo mkdir /home/meteor/logs
sudo chown meteor:meteor /home/meteor/logs/
sudo bash -c 'echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list'
sudo apt-get update
sudo apt-get -t jessie-backports install nginx-full
wget https://git.thm.de/arsnova/arsnova.click/raw/server-config/config/app-server/etc/nginx/sites-available/meteor
sed -i 's/yourdomain.com/\_/' meteor
sudo mv meteor /etc/nginx/sites-available
sudo ln -s /etc/nginx/sites-available/meteor /etc/nginx/sites-enabled/meteor
sudo rm /etc/nginx/sites-enabled/default 
sudo systemctl enable nginx.service
sudo systemctl start nginx.service
systemctl status nginx.service

echo "=== Install ARSnova.click ==="
wget https://git.thm.de/arsnova/arsnova.click/builds/artifacts/master/download?job=build -O artifacts.zip
unzip artifacts.zip -d .
rm artifacts.zip
sudo mv build /home/arsnova

## The content of this file need to be inside of the systemd start sccript
#wget https://git.thm.de/arsnova/arsnova.click/raw/staging/arsnova.click/settings.json
##

sudo cp usr/lib/systemd/system/arsnova-click.service /etc/systemd/system/arsnova-click.service
sudo systemctl daemon-reload
sudo systemctl enable arsnova-click.service
systemctl status arsnova-click.service
sudo systemctl start arsnova-click.service
systemctl status arsnova-click.service

echo "=== Update Raspbian ==="
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

sudo cp etc/dhcpcd.conf /etc/

sudo reboot

exit
